import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="bg-gray-950 text-white min-h-screen font-sans">
        <nav className="bg-gray-800 text-white p-4 flex justify-center gap-8">
          <Link href="/" className="hover:text-cyan-400">Home</Link>
          <Link href="/about" className="hover:text-cyan-400">Sobre</Link>
          <Link href="/contact" className="hover:text-cyan-400">Contato</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}

